{"name": "新增客户失败-用户名为空", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\nrun.py:120: AssumptionFailure\n>>\tpytest.assume(actual_res==expect_res,f'期望是{expect_res},实际是{actual_res}')\nAssertionError: 期望是1,实际是0\nassert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               run.py:120: AssumptionFailure\nE               >>\tpytest.assume(actual_res==expect_res,f'期望是{expect_res},实际是{actual_res}')\nE               AssertionError: 期望是1,实际是0\nE               assert False\n\nD:\\Programs\\Python\\python310\\lib\\site-packages\\six.py:718: FailedAssumption"}, "attachments": [{"name": "log", "source": "72261180-65ac-4c62-ab46-4a4a531447e5-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "suite_name", "value": "'新增客户接口测试集合'"}, {"name": "case_name", "value": "'新增客户失败-用户名为空'"}, {"name": "case_info_list", "value": "[['新增客户', '${host}/CrmCustomer/addOrUpdate', 'post', '{\\n\"Admin-Token\":\"${token}\"\\n}', '{\\n\"json\":{\\n\"$.entity.customer_name\":\"\",\\n}\\n}', '', 200, '[\\n{\\n\"actual\":\"$.code\",\\n\"expect\":1\\n}\\n]']]"}], "start": 1652325210786, "stop": 1652325210853, "uuid": "e94884d8-10f9-45fd-a09b-5921bd919b73", "historyId": "97d85ece36ca31d8218f2693832b3539", "testCaseId": "581fcf0b30a85e3d611d5f9973144474", "fullName": "run#test_run", "labels": [{"name": "feature", "value": "新增客户接口测试集合"}, {"name": "suite", "value": "run"}, {"name": "host", "value": "LAPTOP-93HH27QA"}, {"name": "thread", "value": "17100-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "run"}]}